Repository zcash/halo2, pull requests merged in 2021-07, with the labels that each got.

#316 Final ZK changes
  .github/workflows/ci.yml
  benches/plonk.rs
  examples/circuit-layout.rs
  examples/simple-example.rs
  examples/two-chip.rs
  src/circuit.rs
  src/circuit/floor_planner/single_pass.rs
  src/circuit/floor_planner/v1.rs
  src/circuit/layouter.rs
  src/dev.rs
  src/dev/graph.rs
  src/dev/graph/layout.rs
  src/plonk.rs
  src/plonk/circuit.rs
  src/plonk/keygen.rs
  src/plonk/lookup.rs
  src/plonk/lookup/prover.rs
  src/plonk/lookup/verifier.rs
  src/plonk/permutation.rs
  src/plonk/permutation/keygen.rs
  src/plonk/permutation/prover.rs
  src/plonk/permutation/verifier.rs
  src/plonk/prover.rs
  src/plonk/vanishing/prover.rs
  src/plonk/vanishing/verifier.rs
  src/plonk/verifier.rs
  src/poly.rs
  src/poly/domain.rs
  src/poly/multiopen.rs
  src/poly/multiopen/verifier.rs
  tests/plonk_api.rs
Labels: S-committed

#336 dev: Enable visualizing equality constraints in circuit layouts
  src/dev/graph/layout.rs
Labels: C-dev-tooling

#352 `Expression::Negated`
  benches/plonk.rs
  examples/circuit-layout.rs
  examples/simple-example.rs
  examples/two-chip.rs
  src/dev.rs
  src/plonk/circuit.rs
  src/plonk/circuit/compress_selectors.rs
  src/plonk/lookup/prover.rs
  src/plonk/lookup/verifier.rs
  src/plonk/prover.rs
  src/plonk/verifier.rs
  src/poly.rs
  tests/plonk_api.rs
Labels: I-performance
