Repository zcash/halo2, pull requests merged in 2021-11, with the labels that each got.

#375 Update `dev-graph` examples
  book/src/user/dev-tools.md
  examples/circuit-layout.rs
Labels: A-book

#403 Improve error message when `k` is too small
  CHANGELOG.md
  Cargo.toml
  src/dev.rs
  src/dev/graph/layout.rs
  src/plonk/error.rs
  src/plonk/keygen.rs
  src/plonk/prover.rs
  tests/plonk_api.rs
Labels: A-dev-tooling, A-errors

#385 Introduce plonk::Error::ColumnNotInPermutation error.
  src/plonk/error.rs
  src/plonk/permutation/keygen.rs
Labels: A-errors

#410 Add missing CHANGELOG entry
  CHANGELOG.md
Labels: A-dev-tooling

#383 circuit.rs: Introduce `AssignedCell` struct.
  benches/plonk.rs
  examples/circuit-layout.rs
  examples/simple-example.rs
  examples/two-chip.rs
  src/circuit.rs
  src/plonk/circuit.rs
  tests/plonk_api.rs
Labels: S-committed
