Repository zcash/halo2, pull requests merged in 2022-05, with the labels that each got.

#542 Relicense Halo 2 crates as MIT OR Apache 2.0
  COPYING
  COPYING.md
  Contributor_Agreement
  LICENSE-APACHE
  LICENSE-BOSL
  LICENSE-MIT
  README.md
  halo2/Cargo.toml
  halo2_gadgets/Cargo.toml
  halo2_gadgets/README.md
  halo2_proofs/Cargo.toml
  halo2_proofs/README.md
Labels: S-committed

#543 Optimize Fft
  halo2_proofs/src/arithmetic.rs
Labels: I-performance

#380 [book] Fix errors and typos
  .DS_Store
  book/src/background/curves.md
  book/src/background/fields.md
  book/src/background/groups.md
  book/src/background/pc-ipa.md
  book/src/background/polynomials.md
  book/src/background/recursion.md
  book/src/design/gadgets/sha256/table16.md
  book/src/design/implementation/proofs.md
  book/src/design/protocol.md
  book/src/design/proving-system/comparison.md
  book/src/design/proving-system/lookup.md
  book/src/design/proving-system/multipoint-opening.md
  book/src/user/tips-and-tricks.md
Labels: S-committed

#522 [ECC gadget] Distinguish base field element case in variable-base scalar mul.
  halo2_gadgets/CHANGELOG.md
  halo2_gadgets/src/ecc.rs
  halo2_gadgets/src/ecc/chip.rs
  halo2_gadgets/src/ecc/chip/mul.rs
Labels: S-committed, A-api
