Repository zcash/halo2, pull requests merged in 2022-04, with the labels that each got.

#549 cost-model.rs: Correct lookup required degree calculation.
  halo2_proofs/examples/cost-model.rs
Labels: S-committed

#532 Bench heavily padded lookup in MockProver.
  halo2_proofs/Cargo.toml
  halo2_proofs/benches/dev_lookup.rs
Labels: S-committed

#445 Fix mock prover performance regression for lookup arguments
  halo2_proofs/src/dev.rs
Labels: S-committed, I-performance, A-dev-tooling

#480 Add `MockProver::assert_satisfied` with pretty-printed failures
  halo2_gadgets/src/ecc/chip/mul_fixed/short.rs
  halo2_gadgets/src/utilities/decompose_running_sum.rs
  halo2_proofs/CHANGELOG.md
  halo2_proofs/src/dev.rs
  halo2_proofs/src/dev/failure.rs
  halo2_proofs/src/dev/failure/emitter.rs
  halo2_proofs/src/dev/metadata.rs
  halo2_proofs/src/dev/util.rs
Labels: S-committed, A-dev-tooling, A-errors

#414 Add a `Constraints` helper
  halo2_gadgets/src/sha256/table16/compression/compression_gates.rs
  halo2_proofs/CHANGELOG.md
  halo2_proofs/src/plonk/circuit.rs
Labels: A-api

#557 Fix Halo 2 book deployment
  .github/workflows/book.yml
Labels: A-book, A-CI

#558 CI: Pass the correct `katex-header.html` path to rustdoc
  .github/workflows/book.yml
Labels: C-bug, A-CI

#556 halo2_gadgets: Migrate chip gates to `Constraints::with_selector`
  halo2_gadgets/src/ecc/chip/add.rs
  halo2_gadgets/src/ecc/chip/add_incomplete.rs
  halo2_gadgets/src/ecc/chip/mul.rs
  halo2_gadgets/src/ecc/chip/mul/complete.rs
  halo2_gadgets/src/ecc/chip/mul/incomplete.rs
  halo2_gadgets/src/ecc/chip/mul/overflow.rs
  halo2_gadgets/src/ecc/chip/mul_fixed.rs
  halo2_gadgets/src/ecc/chip/mul_fixed/base_field_elem.rs
  halo2_gadgets/src/ecc/chip/mul_fixed/full_width.rs
  halo2_gadgets/src/ecc/chip/mul_fixed/short.rs
  halo2_gadgets/src/ecc/chip/witness_point.rs
  halo2_gadgets/src/poseidon/pow5.rs
  halo2_gadgets/src/sinsemilla/chip.rs
  halo2_gadgets/src/sinsemilla/merkle/chip.rs
  halo2_gadgets/src/utilities.rs
  halo2_gadgets/src/utilities/cond_swap.rs
  halo2_gadgets/src/utilities/decompose_running_sum.rs
  halo2_gadgets/src/utilities/lookup_range_check.rs
Labels: C-cleanup

#565 CI: Fix Rust version used for benchmarks
  .github/workflows/bench.yml
Labels: A-CI
