Repository zcash/halo2, pull requests merged in 2023-01, with the labels that each got.

#721 Update the status of support for nested web workers in Safari
  book/src/user/wasm-port.md
Labels: A-book

#722 [book] Fix typo in description of Pedersen commitments
  book/src/background/groups.md
Labels: F-nightly

#723 bug fix - wasm pack compile error
  halo2_gadgets/src/poseidon/primitives/mds.rs
Labels: C-bug
